### ISSUE TITLE
Email verification system

### ISSUE THREAD

**Issue by leoleoasd** [EduOJ/backend#119]
- [x] [Backend] Change email when not verified
    - [x] Test
- [x] [Frontend] Redirect to verification page on "NEED_VERIFICATION"
- [x] [Frontend] Resend verification code
- [x] [Frontend] Verify
- [x] [Frontend] Change email
- [x] [Frontned] Reset password

**Comment by littlebear0729** [comment]
All done

**Comment by littlebear0729** [comment]
Finished in https://github.com/EduOJ/frontend/pull/9 and https://github.com/EduOJ/backend/pull/120
