### ISSUE TITLE
成绩查询

### ISSUE THREAD

**Issue by suntt2019** [EduOJ/backend#132]
### 需求
* Class管理员，查询该Class中全部ProblemSet的全部用户成绩
* Class管理员，查询该Class中某一ProblemSet的全部用户成绩
* Class成员，查询该Class中某一ProblemSet的自己的成绩

### Resource
- [ ] **ProblemSetSummaryWithGrades** 用于获取Class时需要携带Grade的情况
    ```go
    type ProblemSetSummary struct {
	    ID uint `json:"id"`
    
	    ClassID     uint   `json:"class_id"`
	    Name        string `json:"name"`
	    Description string `json:"description"`

	    Grades   []Grade          `json:"grades"`  // Additional field than ProblemSetSummary
    
	    StartTime time.Time `json:"start_time"`
	    EndTime   time.Time `json:"end_time"`
    }
    ```

### API
- [x] **GetClassGrades** GET /api/class/:id/grades
  * middleware：同`routes.go/manageClass`
    * 参数检查：`id`为整数
    * 鉴权：已登录，已认证邮箱，有全局或该class的`manage_grades`权限
  * controller：获取全部指定Class的Grade并返回
    * 读取DB：Find `SELECT * FROM grades WHERE class_id = ?;`
- [x] GET /api/class/:class_id/problem_set/:id/grades
  * middleware：同`routes.go/manageProblemSet`
    * 参数检查：`class_id`和`id`为整数
    * 鉴权：已登录，已认证邮箱，有全局或该class的`manage_grades`权限
  * controller：获取全部指定ProblemSet的Grade并返回
    * 读取DB：Find `SELECT * FROM grades WHERE problem_set_id = ?;`
- [ ] **GetClass**(Edit) GET /api/class/:id
  * controller：若非管理员，各ProblemSet附带自己的Grade并随之返回（resource.ProblemSetSummaryWithGrades）
    * 判断：非管理员用户
    * 读取DB：First `SELECT * FROM grades WHERE problem_set_id = ? and user_id = ?;`
- [ ] **GetProblemSet**(Edit) GET /api/class/:class_id/problem_set/:id
  * controller：若非管理员，获取ProblemSet时附带自己的Grade并随之返回（resource.ProblemSetWithGrades）
    * 判断：非管理员用户
    * 读取DB：First `SELECT * FROM grades WHERE problem_set_id = ? and user_id = ?;`
- [ ] **EditGrade** POST /api/class/:class_id/problemset/:id/grade/edit
  * nontrivial request：包含`user_id`(uint)、`problem_id`(uint)、`score`(uint)
  * middleware：同`routes.go/manageProblemSet`
    * 参数检查：`class_id`和`id`为整数
    * 鉴权：已登录，已认证邮箱，有全局或该class的`manage_grades`权限
  * controller：获取全部指定ProblemSet的Grade并返回
    * 解析请求：获取`user_id`、`problem_id`和 `score`
    * 读取DB：First `SELECT * FROM grades WHERE problem_set_id = ? and user_id = ?;`
      * 若未获得Grade则新建并为将分数均填`0`
    * 数据处理：更新该Grade中的此Problem的成绩
    * 写入DB：Save `grade`

**Comment by leoleoasd** [comment]
有没有必要，权限设置成单独的 manage_grades 之类的🤔

**Comment by suntt2019** [comment]
> 有没有必要，权限设置成单独的 manage_grades 之类的🤔

倒是也可以，把前两个API的鉴权改成`manage_grades`？

**Comment by leoleoasd** [comment]
然后获取自己的分数，是不是可以直接合并到 获取homework 的api里🤔 额外返回一个分数

**Comment by suntt2019** [comment]
嗯，可以啊，这个Grade加到Response这样？
```go
type GetProblemSetResponse struct {
	Message string      `json:"message"`
	Error   interface{} `json:"error"`
	Data    struct {
		*resource.ProblemSet `json:"problem_set"`
                *resource.Grade `json:"grade"` // new
	} `json:"data"`
}
```

**Comment by leoleoasd** [comment]
嗯嗯

> 嗯，可以啊，这个Grade加到Response这样？
> 
> ```go
> type GetProblemSetResponse struct {
> 	Message string      `json:"message"`
> 	Error   interface{} `json:"error"`
> 	Data    struct {
> 		*resource.ProblemSet `json:"problem_set"`
>                 *resource.Grade `json:"grade"` // new
> 	} `json:"data"`
> }
> ```

**Comment by leoleoasd** [comment]
应该是类似 ProblemSetWithGrades， 把同学访问 getclass 和 getproblemset 的返回都加一个这个同学自己的grades

**Comment by leoleoasd** [comment]
getproblemset应该就只有一个grade， getclass应该是里面的每个problemset有一个grade？

**Comment by leoleoasd** [comment]
`GetProblemSetGrades` 似乎已经写过了
https://github.com/EduOJ/backend/blob/dev/any_language/app/routes.go#L294

**Comment by suntt2019** [comment]
> getproblemset应该就只有一个grade， getclass应该是里面的每个problemset有一个grade？

嗯，既然这样的话要不把这个Grade加到`resource.ProblemSet`里？不过这样的话`conver`的时候就要额外加一个`grade`参数，不知道这样是否违背`resource`的设计初衷

要素加到response里的话，就是problem set和grade两个list，然后显示的时候再zip一下，感觉好像也有点奇怪

**Comment by leoleoasd** [comment]
> 嗯，既然这样的话要不把这个Grade加到resource.ProblemSet里？不过这样的话conver的时候就要额外加一个grade参数，不知道这样是否违背resource的设计初衷
感觉可以，问题不大

**Comment by suntt2019** [comment]
> `GetProblemSetGrades` 似乎已经写过了 https://github.com/EduOJ/backend/blob/dev/any_language/app/routes.go#L294

Ok，那我去把它重命名为`GetProblemSetGrades`吧

**Comment by suntt2019** [comment]
欸，原来之前写过一个`ProblemSetWithGrades`，里面是包含Grades的ProblemSet，那要不给普通用户返回只包含一个Grade的`ProblemSetWithGrades`吧

**Comment by leoleoasd** [comment]
🤔 也行
