### ISSUE TITLE
改进成绩系统

### ISSUE THREAD

**Issue by suntt2019** [EduOJ/backend#78]
# Improve Grade

### Permission

|         Name         |                                                 Description                                                 |
|:--------------------:|:-----------------------------------------------------------------------------------------------------------:|
|     read_answers     |                                         read submissions in a class                                         |

### Resources

* **ProblemSetWithGrades**
  * 包含基础信息（`ID`, `ClassID`, `Name`, `Discription`, `StartTime`, `EndTime`）
  * 包含题目信息（无题目描述）
  * 包含成绩信息（该`ProblemSet`中所有`Grade`）

### API

* **GetGrades** GET /api/class/:class_id/problem_set/:id/grades
  * 功能：获取指定`ProblemSet`的所有成绩，未提交的创建0分`Grade`
  * 权限：必须具有全局或针对该班级的`read_answers`权限
  * 请求：Request为空
  * 响应：返回该`ProblemSet`的`ProblemSetWithGrades`
  
* **RefreshGrades** PUT /api/class/:class_id/problem_set/:id/grades

  * 功能：根据`Submission`重新计算该`ProblemSet`的所有`Grades`，未提交的创建0分`Grade`

  * 权限：必须具有全局或针对该班级的`read_answers`权限
  * 请求：Request为空
  * 响应：返回该`ProblemSet`的`ProblemSetWithGrades`

**Comment by leoleoasd** [comment]
update改成refresh？🤔
update是改分用的吧

**Comment by lbh2001** [comment]
你好，我正在尝试完成这两个功能，我在 permissions table 中没看到名为“全局权限”的permission。读了部分源码后发现有ScopePermission 和 UnScopePermission 两个中间件，所以是否是针对两个api，需要有ScopePermission或UnScopePermission两种作用域下的read_answers 权限即可？

**Comment by leoleoasd** [comment]
> 你好，我正在尝试完成这两个功能，我在 permissions table 中没看到名为“全局权限”的permission。读了部分源码后发现有ScopePermission 和 UnScopePermission 两个中间件，所以是否是针对两个api，需要有ScopePermission或UnScopePermission两种作用域下的read_answers 权限即可？

对的。ScopedPermission指的是`target`不是`nil`的`role`的`permission`。 UnscopedPermisison相反。
比如，全局管理员拥有UnscopedPermission，某个班级的管理员有ScopedPermission。

**Comment by lbh2001** [comment]
```go
type Grade struct {
	ID uint `gorm:"primaryKey" json:"id"`

	UserID       uint        `json:"user_id"`
	User         *User       `json:"user"`
	ProblemSetID uint        `json:"problem_set_id"`
	ProblemSet   *ProblemSet `json:"problem_set"`
	ClassID      uint        `json:"class_id"`
	Class        *Class      `json:"class"`

	Detail datatypes.JSON `json:"detail"`
	Total  uint           `json:"total"`

	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"-"`
	DeletedAt gorm.DeletedAt `json:"deleted_at"`
}
```
您好，`Grade`结构体中的`Total`字段是总分的意思嘛？

**Comment by leoleoasd** [comment]
@lbh2001 是的。
